name: nnnn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: 4.2.0
  table_calendar: ^3.2.0
  http: ^1.3.0
  intl: ^0.20.2
  fluttertoast: ^8.2.12
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.4
  url_launcher: ^6.2.5






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

